image: daewok/lisp-devel

stages:
  - build
  - test

before_script:
  - apt-get update -qy
  - apt-get install -y git-core
  - cp -r /builds/ediethelm/trivial-object-lock ~/quicklisp/local-projects/trivial-object-lock
  - git clone https://gitlab.com/ediethelm/trivial-utilities.git ~/quicklisp/local-projects/trivial-utilities
  - git clone https://gitlab.com/ediethelm/trivial-coverage.git ~/quicklisp/local-projects/trivial-coverage


sbcl-build:
  stage: build
  script:
    - sbcl --non-interactive --eval "(ql:quickload :trivial-object-lock)"

ccl-build:
  stage: build
  script:
    - ccl --eval "(let ((*debugger-hook* (lambda (c m)
                                           (declare (ignore c m))
                                           (uiop:quit 1))))
                    (ql:quickload :trivial-object-lock))"

sbcl-test:
  stage: test
  coverage: '/Test coverage: (\d+\.\d+)%/'
  script:
    - sbcl --non-interactive --eval "(progn 
                                       (ql:quickload :trivial-coverage)
                                       (ql:quickload :trivial-object-lock/test)
                                       (uiop:symbol-call :trivial-coverage
                                         '#:test-and-print-coverage
                                         :trivial-object-lock
                                         :exclude '(\"test-trivial-object-lock.lisp\" 
                                                    \"documentation.lisp\"
                                                    \"package.lisp\")
                                         :keep-report t))"
